<script setup lang="ts">
import { ref, onMounted } from 'vue';

const osName = ref('your system');
const downloadUrl = ref('https://github.com/open-agent3/agent3/releases/latest');
const isLoading = ref(true);

function getOS(): 'win' | 'mac' | 'linux' | 'other' {
  const userAgent = window.navigator.userAgent;
  if (userAgent.indexOf("Win") !== -1) return "win";
  if (userAgent.indexOf("Mac") !== -1) return "mac";
  if (userAgent.indexOf("Linux") !== -1) return "linux";
  return "other";
}

onMounted(async () => {
  const os = getOS();

  // Set friendly OS name for the button immediately
  if (os === 'win') osName.value = 'Windows';
  else if (os === 'mac') osName.value = 'macOS';
  else if (os === 'linux') osName.value = 'Linux';

  try {
    // Read via GitHub API to avoid raw GitHub Releases CORS issues
    const response = await fetch('https://api.github.com/repos/open-agent3/agent3/releases/latest');
    if (response.ok) {
      const data = await response.json();
      const assets = data.assets || [];

      // Determine correct extension based on platform
      // Prioritizing specific formats generated by Tauri
      const extensionMap: Record<string, string[]> = {
        'win': ['.exe', '.msi'],
        'mac': ['.dmg', '.app.tar.gz'],
        'linux': ['.AppImage', '.deb']
      };

      if (os !== 'other') {
        const targetExts = extensionMap[os];
        // Find the first matching asset that ends with one of our preferred extensions
        const matchedAsset = assets.find((asset: any) => 
          targetExts.some(ext => asset.name.endsWith(ext))
        );

        if (matchedAsset) {
          downloadUrl.value = matchedAsset.browser_download_url;
        }
      }
    }
  } catch (error) {
    console.warn('Failed to fetch latest release via API:', error);
  } finally {
    isLoading.value = false;
  }
});
</script>

<template>
  <div class="download-container">
    <a :href="downloadUrl" class="btn primary" :class="{ loading: isLoading }">
      {{ isLoading ? 'Checking Latest Version...' : `Download for ${osName}` }}
    </a>
    <a href="/ARCHITECTURE" class="btn alt">
      Documentation
    </a>
    <a href="https://github.com/open-agent3/agent3" class="btn secondary" target="_blank" rel="noopener">
      View on GitHub
    </a>
  </div>
</template>

<style scoped>
.download-container {
  display: flex;
  gap: 1.5rem;
  justify-content: center;
  align-items: center;
  margin-top: 3rem;
  z-index: 10;
  position: relative;
  flex-wrap: wrap; /* allow wrapping on smaller screens */
}

.btn {
  display: inline-flex;
  padding: 14px 32px;
  border-radius: 99px;
  text-decoration: none;
  font-weight: 500;
  font-size: 1.1rem;
  transition: all 0.3s cubic-bezier(0.25, 0.8, 0.25, 1);
  letter-spacing: 0.5px;
}

.btn.primary {
  background: var(--vp-c-brand-1);
  color: #fff;
  box-shadow: 0 0 20px rgba(255, 81, 47, 0.4);
}

.btn.primary:hover {
  transform: translateY(-2px);
  box-shadow: 0 0 30px rgba(255, 81, 47, 0.6);
  background: var(--vp-c-brand-2);
}

.btn.alt {
  color: var(--vp-c-text-1);
  background: var(--vp-c-brand-soft);
  border: 1px solid rgba(255, 81, 47, 0.2);
  backdrop-filter: blur(10px);
}

.btn.alt:hover {
  background: rgba(255, 81, 47, 0.15);
  border-color: rgba(255, 81, 47, 0.3);
  transform: translateY(-2px);
}

.btn.secondary {
  color: var(--vp-c-text-2);
  background: transparent;
  border: 1px solid transparent;
}

.btn.secondary:hover {
  color: var(--vp-c-text-1);
  background: rgba(255, 255, 255, 0.05);
  transform: translateY(-2px);
}

.btn.loading {
  opacity: 0.7;
  pointer-events: none;
  cursor: wait;
}
</style>
